# to run any of these, follow the setup instructions, then call `resource_manage [pipeline task]`. For example:
# > resource_manage 1.7_dev_soartex

download_default = [
    # mods
    {task = "run_pipeline", pipeline = "download_1k_mods"},

    # vanilla packs
    {task = "download_resource", resource = "default-vanilla-1.5.x"},
    {task = "download_resource", resource = "default-vanilla-1.7.x"},
    {task = "download_resource", resource = "default-vanilla-1.10.x"},
    {task = "download_resource", resource = "default-vanilla-1.12.x"},
]

download_soartex = [
    {task = "download_resource", resource = "fanver-modded-1.5.x"},
    {task = "download_resource", resource = "fanver-modded-1.7.x"},
    {task = "download_resource", resource = "fanver-modded-1.10.x"},
    {task = "download_resource", resource = "fanver-modded-1.12.x"},

    {task = "download_resource", resource = "fanver-vanilla-1.5.x"},
    {task = "download_resource", resource = "fanver-vanilla-1.7.x"},
    {task = "download_resource", resource = "fanver-vanilla-1.10.x"},
    {task = "download_resource", resource = "fanver-vanilla-1.12.x"},

    {task = "download_resource", resource = "invictus-vanilla-1.7.x"},
    {task = "download_resource", resource = "invictus-vanilla-1.12.x"},

    # misc
    {task = "download_resource", resource = "fanver-modded-base"},
    {task = "download_resource", resource = "gtnh-1.7.x"},
    {task = "download_resource", resource = "invictus-modded-1.7.x"},
]

download_jstr = [
    {task = "download_resource", resource = "jstr-modded-1.5.x"},
    {task = "download_resource", resource = "jstr-modded-1.7.x"},
    {task = "download_resource", resource = "jstr-modded-1.10.x"},
    {task = "download_resource", resource = "jstr-modded-1.12.x"},

    {task = "download_resource", resource = "jstr-vanilla-1.7.x"},
    {task = "download_resource", resource = "jstr-vanilla-1.10.x"},
    {task = "download_resource", resource = "jstr-vanilla-1.12.x"},
]

download_all = [
    {task = "run_pipeline", resource = "download_default"},
    {task = "run_pipeline", resource = "download_soartex"},
    {task = "run_pipeline", resource = "download_jstr"}
]

extract_all_default = [
    {task = "extract_default", resource = "default-modded-1.5.x"},
    {task = "extract_default", resource = "default-modded-1.7.x"},
    {task = "extract_default", resource = "default-modded-1.10.x"},
    {task = "extract_default", resource = "default-modded-1.12.x"},
    {task = "extract_default", resource = "default-modded-1.15.x"},
]

merge_all_default = [
    {task = "merge_patches", resource = "default-modded-1.5.x"},
    {task = "merge_patches", resource = "default-modded-1.7.x"},
    {task = "merge_patches", resource = "default-modded-1.10.x"},
    {task = "merge_patches", resource = "default-modded-1.12.x"},
    {task = "merge_patches", resource = "default-modded-1.15.x"},
]

merge_all_soartex = [
    {task = "merge_patches", resource = "fanver-modded-1.5.x"},
    {task = "merge_patches", resource = "fanver-modded-1.7.x"},
    {task = "merge_patches", resource = "fanver-modded-1.10.x"},
    {task = "merge_patches", resource = "fanver-modded-1.12.x"},
    {task = "merge_patches", resource = "invictus-modded-1.7.x"},
]

merge_all_jstr = [
    {task = "merge_patches", resource = "jstr-modded-1.5.x"},
    {task = "merge_patches", resource = "jstr-modded-1.7.x"},
    {task = "merge_patches", resource = "jstr-modded-1.10.x"},
    {task = "merge_patches", resource = "jstr-modded-1.12.x"},
]

port_all_fanver = [
    {task = "run_pipeline", pipeline = "1.5_to_1.5_port_fanver" },
    {task = "run_pipeline", pipeline = "1.5_to_1.7_port_fanver" },
    {task = "run_pipeline", pipeline = "1.7_to_1.7_port_fanver" },
    {task = "run_pipeline", pipeline = "1.7_to_1.10_port_fanver" },
    {task = "run_pipeline", pipeline = "1.10_to_1.10_port_fanver" },
    {task = "run_pipeline", pipeline = "1.7_to_1.12_port_fanver" },
    {task = "run_pipeline", pipeline = "1.10_to_1.12_port_fanver" },
    {task = "run_pipeline", pipeline = "1.12_to_1.12_port_fanver" },
    {task = "run_pipeline", pipeline = "1.12_to_1.15_port_fanver" }
]

back_port_all_fanver = [
    {task = "run_pipeline", pipeline = "1.12_to_1.10_port_fanver" },
    {task = "run_pipeline", pipeline = "1.10_to_1.7_port_fanver" },
    {task = "run_pipeline", pipeline = "1.12_to_1.7_port_fanver" },
    {task = "run_pipeline", pipeline = "1.7_to_1.5_port_fanver" },
]

port_all_jstr = [
    {task = "run_pipeline", pipeline = "1.5_to_1.5_port_jstr" },
    {task = "run_pipeline", pipeline = "1.5_to_1.7_port_jstr" },
    {task = "run_pipeline", pipeline = "1.7_to_1.7_port_jstr" },
    {task = "run_pipeline", pipeline = "1.7_to_1.10_port_jstr" },
    {task = "run_pipeline", pipeline = "1.10_to_1.10_port_jstr" },
    {task = "run_pipeline", pipeline = "1.7_to_1.12_port_jstr" },
    {task = "run_pipeline", pipeline = "1.10_to_1.12_port_jstr" },
    {task = "run_pipeline", pipeline = "1.12_to_1.12_port_jstr" },
    {task = "run_pipeline", pipeline = "1.12_to_1.15_port_jstr" }
]

back_port_all_jstr = [
    {task = "run_pipeline", pipeline = "1.12_to_1.10_port_jstr" },
    {task = "run_pipeline", pipeline = "1.10_to_1.7_port_jstr" },
    {task = "run_pipeline", pipeline = "1.12_to_1.7_port_jstr" },
    {task = "run_pipeline", pipeline = "1.7_to_1.5_port_jstr" },
]

prune_all_fanver = [
    {task = "prune_files", action = "prune", resource = "fanver-modded-1.5.x", resource_default = "default-modded-1.5.x", pruned_dir = "~/graphics/fanver/Pruned-1.5.x"},
    {task = "prune_files", action = "prune", resource = "fanver-modded-1.7.x", resource_default = "default-modded-1.7.x", pruned_dir = "~/graphics/fanver/Pruned-1.7.x"},
    {task = "prune_files", action = "prune", resource = "fanver-modded-1.10.x", resource_default = "default-modded-1.10.x", pruned_dir = "~/graphics/fanver/Pruned-1.10.x"},
    {task = "prune_files", action = "prune", resource = "fanver-modded-1.12.x", resource_default = "default-modded-1.12.x", pruned_dir = "~/graphics/fanver/Pruned-1.12.x"},
]

prune_all_jstr = [
    {task = "prune_files", action = "prune", resource = "jstr-modded-1.5.x", resource_default = "default-modded-1.5.x", pruned_dir = "~/graphics/jstr/Pruned-1.5.x"},
    {task = "prune_files", action = "prune", resource = "jstr-modded-1.7.x", resource_default = "default-modded-1.7.x", pruned_dir = "~/graphics/jstr/Pruned-1.7.x"},
    {task = "prune_files", action = "prune", resource = "jstr-modded-1.10.x", resource_default = "default-modded-1.10.x", pruned_dir = "~/graphics/jstr/Pruned-1.10.x"},
    {task = "prune_files", action = "prune", resource = "jstr-modded-1.12.x", resource_default = "default-modded-1.12.x", pruned_dir = "~/graphics/jstr/Pruned-1.12.x"},
]

omni_update_soartex = [
    {task = "run_pipeline", pipeline = "download_default"},
    {task = "run_pipeline", pipeline = "download_soartex"},
    {task = "run_pipeline", pipeline = "extract_all_default"},
    {task = "run_pipeline", pipeline = "merge_all_default"},
    {task = "run_pipeline", pipeline = "merge_all_soartex"},
    {task = "run_pipeline", pipeline = "port_all_fanver" },
    {task = "run_pipeline", pipeline = "back_port_all_fanver" },
    {task = "run_pipeline", pipeline = "prune_all_fanver" }
]

omni_update_jstr = [
    {task = "run_pipeline", pipeline = "download_default"},
    {task = "run_pipeline", pipeline = "download_jstr"},
    {task = "run_pipeline", pipeline = "extract_all_default"},
    {task = "run_pipeline", pipeline = "merge_all_default"},
    {task = "run_pipeline", pipeline = "merge_all_jstr"},
    {task = "run_pipeline", pipeline = "port_all_jstr" },
    {task = "run_pipeline", pipeline = "back_port_all_jstr" },
    {task = "run_pipeline", pipeline = "prune_all_jstr" }
]

omni_update = [
    {task = "run_pipeline", pipeline = "download_default"},
    {task = "run_pipeline", pipeline = "download_soartex"},
    {task = "run_pipeline", pipeline = "download_jstr"},
    {task = "run_pipeline", pipeline = "extract_all_default"},
    {task = "run_pipeline", pipeline = "merge_all_default"},
    {task = "run_pipeline", pipeline = "merge_all_soartex"},
    {task = "run_pipeline", pipeline = "merge_all_jstr"},
    {task = "run_pipeline", pipeline = "port_all_fanver"},
    {task = "run_pipeline", pipeline = "back_port_all_fanver"},
    {task = "run_pipeline", pipeline = "port_all_jstr"},
    {task = "run_pipeline", pipeline = "back_port_all_jstr"},

#    {task = "run_pipeline", pipeline = "prune_all_fanver"},
#    {task = "run_pipeline", pipeline = "prune_all_jstr"}
]

"1.7_merge_fanver" = [
    {task = "remove_resource", resource = "fanver-modded-1.7.x", folder = "pack_dir"},
    {task = "merge_patches", resource = "fanver-modded-1.7.x"},
]

"1.7_extract" = [
    {task = "remove_resource", resource = "default-modded-1.7.x", folder = "pack_dir"},
    {task = "extract_default", resource = "default-modded-1.7.x"},
    {task = "merge_patches", resource = "default-modded-1.7.x"}
]

"1.7_dev_soartex" = [
#    {task = "extract_default", resource = "default-modded-1.7.x"},

    # build merged resource packs from the patch directories
    {task = "merge_patches", resource = "fanver-modded-1.7.x"},
    {task = "merge_patches", resource = "invictus-modded-1.7.x"},

    # link all texture packs with relevant game instances
    {task = "link_resources", resource = "fanver-vanilla-1.7.x"},
    {task = "link_resources", resource = "fanver-modded-1.7.x"},
    {task = "link_resources", resource = "invictus-vanilla-1.7.x"},
    {task = "link_resources", resource = "invictus-modded-1.7.x"},
    {task = "link_resources", resource = "gtnh-1.7.x"},

    # watch for changes/update merged packs in any of the specified resources
    {task = "watch_changes", resources = ["fanver-modded-1.7.x", "invictus-modded-1.7.x"]}
]

"1.12_dev_soartex" = [
#    {task = "extract_default", resource = "default-modded-1.12.x"},

    # build merged resource packs from the patch directories
    {task = "merge_patches", resource = "fanver-modded-1.12.x"},
    {task = "merge_patches", resource = "fanver-modded-base"},

    # link all texture packs with relevant game instances
    {task = "link_resources", resource = "invictus-vanilla-1.12.x"},
    {task = "link_resources", resource = "fanver-vanilla-1.12.x"},
    {task = "link_resources", resource = "fanver-modded-base"},
    {task = "link_resources", resource = "fanver-modded-1.12.x"},

    # watch for changes/update merged packs in any of the specified resources
    {task = "watch_changes", resources = ["fanver-modded-base", "fanver-modded-1.12.x"]}
]

"1.12_dev_jstr" = [
#    {task = "extract_default", resource = "default-modded-1.12.x"},

    # build merged resource packs from the patch directories
    {task = "merge_patches", resource = "jstr-modded-1.12.x"},

    # link all texture packs with relevant game instances
    {task = "link_resources", resource = "jstr-vanilla-1.12.x"},
    {task = "link_resources", resource = "jstr-modded-1.12.x"},

    # watch for changes/update merged packs in any of the specified resources
    {task = "watch_changes", resources = ["jstr-modded-1.12.x"]}
]

"1.12_extract" = [
    {task = "extract_default", resource = "default-modded-1.12.x"},
    {task = "merge_patches", resource = "default-modded-1.12.x"}
]

"1.7_prune_fanver" = [
#    {task = "run_pipeline", pipeline = "1.12_extract"},
    {task = "prune_files", resource = "fanver-modded-1.7.x", resource_default = "default-modded-1.7.x", pruned_dir = "~/graphics/fanver/Pruned-1.7.x", action = "none"}
]

"1.12_prune_fanver" = [
#    {task = "run_pipeline", pipeline = "1.12_extract"},
    {task = "prune_files", resource = "fanver-modded-1.12.x", resource_default = "default-modded-1.12.x", action = "none"}
]

[["download_1k_mods"]]
# up to 1000 mods for each of the five minor versions of minecraft
task = "download_mods"
database_path = "~/graphics/manager/manager.db"
mod_limit = 1000
["download_1k_mods".mods_dirs]
5 = "~/graphics/default/Downloaded-Mods-1.5.x/"
7 = "~/graphics/default/Downloaded-Mods-1.7.x/"
10 = "~/graphics/default/Downloaded-Mods-1.10.x/"
12 = "~/graphics/default/Downloaded-Mods-1.12.x/"
15 = "~/graphics/default/Downloaded-Mods-1.15.x/"


# INTERNAL VERSION PORTS
# for reused vanilla textures
[["1.5_to_1.5_port_fanver"]]
task = "port_patches"
default_prior = "default-vanilla-1.5.x"
default_post = "default-modded-1.5.x"
resource_prior = "fanver-vanilla-1.5.x"
resource_post = "fanver-modded-1.5.x"
action = "copy"
# for modded textures with duplicates
[["1.5_to_1.5_port_fanver"]]
task = "port_patches"
default_prior = "default-modded-1.5.x"
default_post = "default-modded-1.5.x"
resource_prior = "fanver-modded-1.5.x"
resource_post = "fanver-modded-1.5.x"
action = "copy"

[["1.7_to_1.7_port_fanver"]]
task = "port_patches"
default_prior = "default-vanilla-1.7.x"
default_post = "default-modded-1.7.x"
resource_prior = "fanver-vanilla-1.7.x"
resource_post = "fanver-modded-1.7.x"
action = "copy"
[["1.7_to_1.7_port_fanver"]]
task = "port_patches"
default_prior = "default-modded-1.7.x"
default_post = "default-modded-1.7.x"
resource_prior = "fanver-modded-1.7.x"
resource_post = "fanver-modded-1.7.x"
action = "copy"

[["1.10_to_1.10_port_fanver"]]
task = "port_patches"
default_prior = "default-vanilla-1.10.x"
default_post = "default-modded-1.10.x"
resource_prior = "fanver-vanilla-1.10.x"
resource_post = "fanver-modded-1.10.x"
action = "copy"
[["1.10_to_1.10_port_fanver"]]
task = "port_patches"
default_prior = "default-modded-1.10.x"
default_post = "default-modded-1.10.x"
resource_prior = "fanver-modded-1.10.x"
resource_post = "fanver-modded-1.10.x"
action = "copy"

[["1.12_to_1.12_port_fanver"]]
task = "port_patches"
default_prior = "default-vanilla-1.12.x"
default_post = "default-modded-1.12.x"
resource_prior = "fanver-vanilla-1.12.x"
resource_post = "fanver-modded-1.12.x"
action = "copy"
[["1.12_to_1.12_port_fanver"]]
task = "port_patches"
default_prior = "default-modded-1.12.x"
default_post = "default-modded-1.12.x"
resource_prior = "fanver-modded-1.12.x"
resource_post = "fanver-modded-1.12.x"
action = "copy"


# CROSS VERSION PORTS
[["1.5_to_1.7_port_fanver"]]
task = "port_patches"
default_prior = "default-modded-1.5.x"
default_post = "default-modded-1.7.x"
resource_prior = "fanver-modded-1.5.x"
resource_post = "fanver-modded-1.7.x"
action = "copy"

[["1.7_to_1.10_port_fanver"]]
task = "port_patches"
default_prior = "default-modded-1.7.x"
default_post = "default-modded-1.10.x"
resource_prior = "fanver-modded-1.7.x"
resource_post = "fanver-modded-1.10.x"
action = "copy"

[["1.7_to_1.12_port_fanver"]]
task = "port_patches"
default_prior = "default-modded-1.7.x"
default_post = "default-modded-1.12.x"
resource_prior = "fanver-modded-1.7.x"
resource_post = "fanver-modded-1.12.x"
action = "copy"

[["1.10_to_1.12_port_fanver"]]
task = "port_patches"
default_prior = "default-modded-1.10.x"
default_post = "default-modded-1.12.x"
resource_prior = "fanver-modded-1.10.x"
resource_post = "fanver-modded-1.12.x"
action = "copy"

[["1.12_to_1.15_port_fanver"]]
task = "port_patches"
default_prior = "default-modded-1.12.x"
default_post = "default-modded-1.15.x"
resource_prior = "fanver-modded-1.12.x"
resource_post = "fanver-modded-1.15.x"
action = "copy"


# CROSS VERSION BACK PORTS
[["1.12_to_1.10_port_fanver"]]
task = "port_patches"
default_prior = "default-modded-1.12.x"
default_post = "default-modded-1.10.x"
resource_prior = "fanver-modded-1.12.x"
resource_post = "fanver-modded-1.10.x"
action = "copy"

[["1.10_to_1.7_port_fanver"]]
task = "port_patches"
default_prior = "default-modded-1.10.x"
default_post = "default-modded-1.7.x"
resource_prior = "fanver-modded-1.10.x"
resource_post = "fanver-modded-1.7.x"
action = "copy"

[["1.12_to_1.7_port_fanver"]]
task = "port_patches"
default_prior = "default-modded-1.12.x"
default_post = "default-modded-1.7.x"
resource_prior = "fanver-modded-1.12.x"
resource_post = "fanver-modded-1.7.x"
action = "copy"

[["1.7_to_1.5_port_fanver"]]
task = "port_patches"
default_prior = "default-modded-1.7.x"
default_post = "default-modded-1.5.x"
resource_prior = "fanver-modded-1.7.x"
resource_post = "fanver-modded-1.5.x"
action = "copy"




# INTERNAL VERSION PORTS
# for modded textures with duplicates
[["1.5_to_1.5_port_jstr"]]
task = "port_patches"
default_prior = "default-modded-1.5.x"
default_post = "default-modded-1.5.x"
resource_prior = "jstr-modded-1.5.x"
resource_post = "jstr-modded-1.5.x"
action = "copy"

[["1.7_to_1.7_port_jstr"]]
task = "port_patches"
default_prior = "default-vanilla-1.7.x"
default_post = "default-modded-1.7.x"
resource_prior = "jstr-vanilla-1.7.x"
resource_post = "jstr-modded-1.7.x"
action = "copy"
[["1.7_to_1.7_port_jstr"]]
task = "port_patches"
default_prior = "default-modded-1.7.x"
default_post = "default-modded-1.7.x"
resource_prior = "jstr-modded-1.7.x"
resource_post = "jstr-modded-1.7.x"
action = "copy"

[["1.10_to_1.10_port_jstr"]]
task = "port_patches"
default_prior = "default-vanilla-1.10.x"
default_post = "default-modded-1.10.x"
resource_prior = "jstr-vanilla-1.10.x"
resource_post = "jstr-modded-1.10.x"
action = "copy"
[["1.10_to_1.10_port_jstr"]]
task = "port_patches"
default_prior = "default-modded-1.10.x"
default_post = "default-modded-1.10.x"
resource_prior = "jstr-modded-1.10.x"
resource_post = "jstr-modded-1.10.x"
action = "copy"

[["1.12_to_1.12_port_jstr"]]
task = "port_patches"
default_prior = "default-vanilla-1.12.x"
default_post = "default-modded-1.12.x"
resource_prior = "jstr-vanilla-1.12.x"
resource_post = "jstr-modded-1.12.x"
action = "copy"
[["1.12_to_1.12_port_jstr"]]
task = "port_patches"
default_prior = "default-modded-1.12.x"
default_post = "default-modded-1.12.x"
resource_prior = "jstr-modded-1.12.x"
resource_post = "jstr-modded-1.12.x"
action = "copy"


# CROSS VERSION PORTS
[["1.5_to_1.7_port_jstr"]]
task = "port_patches"
default_prior = "default-modded-1.5.x"
default_post = "default-modded-1.7.x"
resource_prior = "jstr-modded-1.5.x"
resource_post = "jstr-modded-1.7.x"
action = "copy"

[["1.7_to_1.10_port_jstr"]]
task = "port_patches"
default_prior = "default-modded-1.7.x"
default_post = "default-modded-1.10.x"
resource_prior = "jstr-modded-1.7.x"
resource_post = "jstr-modded-1.10.x"
action = "copy"

[["1.7_to_1.12_port_jstr"]]
task = "port_patches"
default_prior = "default-modded-1.7.x"
default_post = "default-modded-1.12.x"
resource_prior = "jstr-modded-1.7.x"
resource_post = "jstr-modded-1.12.x"
action = "copy"

[["1.10_to_1.12_port_jstr"]]
task = "port_patches"
default_prior = "default-modded-1.10.x"
default_post = "default-modded-1.12.x"
resource_prior = "jstr-modded-1.10.x"
resource_post = "jstr-modded-1.12.x"
action = "copy"

[["1.12_to_1.15_port_jstr"]]
task = "port_patches"
default_prior = "default-modded-1.12.x"
default_post = "default-modded-1.15.x"
resource_prior = "jstr-modded-1.12.x"
resource_post = "jstr-modded-1.15.x"
action = "copy"


# CROSS VERSION BACK PORTS
[["1.12_to_1.10_port_jstr"]]
task = "port_patches"
default_prior = "default-modded-1.12.x"
default_post = "default-modded-1.10.x"
resource_prior = "jstr-modded-1.12.x"
resource_post = "jstr-modded-1.10.x"
action = "copy"

[["1.10_to_1.7_port_jstr"]]
task = "port_patches"
default_prior = "default-modded-1.10.x"
default_post = "default-modded-1.7.x"
resource_prior = "jstr-modded-1.10.x"
resource_post = "jstr-modded-1.7.x"
action = "copy"

[["1.12_to_1.7_port_jstr"]]
task = "port_patches"
default_prior = "default-modded-1.12.x"
default_post = "default-modded-1.7.x"
resource_prior = "jstr-modded-1.12.x"
resource_post = "jstr-modded-1.7.x"
action = "copy"

[["1.7_to_1.5_port_jstr"]]
task = "port_patches"
default_prior = "default-modded-1.7.x"
default_post = "default-modded-1.5.x"
resource_prior = "jstr-modded-1.7.x"
resource_post = "jstr-modded-1.5.x"
action = "copy"