
# DEFAULT RESOURCES
["default-vanilla-1.5.x"]
jar_path = "/Users/michael/Library/Application Support/minecraft/versions/1.5.2/1.5.2.jar"
patches_dir = "~/graphics/default/Vanilla-1.5.x/"
pack_dir = "~/graphics/default/Vanilla-1.5.x/Vanilla/"

["default-vanilla-1.7.x"]
jar_path = "/Users/michael/Library/Application Support/minecraft/versions/1.7.10/1.7.10.jar"
patches_dir = "~/graphics/default/Vanilla-1.7.x/"
pack_dir = "~/graphics/default/Vanilla-1.7.x/Vanilla/"

["default-vanilla-1.10.x"]
jar_path = "/Users/michael/Library/Application Support/minecraft/versions/1.10.2/1.10.2.jar"
patches_dir = "~/graphics/default/Vanilla-1.10.x/"
pack_dir = "~/graphics/default/Vanilla-1.10.x/Vanilla/"

["default-vanilla-1.12.x"]
jar_path = "/Users/michael/Library/Application Support/minecraft/versions/1.12.2/1.12.2.jar"
patches_dir = "~/graphics/default/Vanilla-1.12.x/"
pack_dir = "~/graphics/default/Vanilla-1.12.x/Vanilla/"

["default-vanilla-1.15.x"]
jar_path = "/Users/michael/Library/Application Support/minecraft/versions/1.15.2/1.15.2.jar"
patches_dir = "~/graphics/default/Vanilla-1.15.x/"
pack_dir = "~/graphics/default/Vanilla-1.15.x/Vanilla/"


["default-modded-1.5.x"]
mods_dirs = [
    "/Applications/MultiMC.app/Contents/MacOS/instances/FTB Unleashed/.minecraft/mods",
    "~/graphics/default/Downloaded-Mods-1.5.x/"
]
patches_dir = "~/graphics/default/Modded-1.5.x/"
pack_dir = "~/graphics_merged/default/Modded-1.5.x/"
pack_format = 1

["default-modded-1.7.x"]
mods_dirs = [
    "/Users/michael/Documents/ATLauncher.app/Contents/Java/instances/BeyondReality/mods",
    "/Applications/MultiMC.app/Contents/MacOS/instances/FTB Infinity Evolved 1.7/mods",
    "/Applications/MultiMC.app/Contents/MacOS/instances/1.7.10/.minecraft/mods",
    "~/graphics/default/Downloaded-Mods-1.7.x/"
]
patches_dir = "~/graphics/default/Modded-1.7.x/"
pack_dir = "~/graphics_merged/default/Modded-1.7.x/"
pack_format = 1

["default-modded-1.10.x"]
mods_dirs = [
    "/Applications/MultiMC.app/Contents/MacOS/instances/FTB Beyond/.minecraft/mods",
    "~/graphics/default/Downloaded-Mods-1.10.x/"
]
patches_dir = "~/graphics/default/Modded-1.10.x/"
pack_dir = "~/graphics_merged/default/Modded-1.10.x/"
pack_format = 2

["default-modded-1.12.x"]
mods_dirs = [
    "/Applications/MultiMC.app/Contents/MacOS/instances/FTB Revelation/.minecraft/mods",
    "/Users/michael/Documents/ATLauncher.app/Contents/Java/instances/SevTechAges/mods",
    "~/graphics/default/Downloaded-Mods-1.12.x/"
]
patches_dir = "~/graphics/default/Modded-1.12.x/"
pack_dir = "~/graphics_merged/default/Modded-1.12.x/"
pack_format = 3

["default-modded-1.15.x"]
mods_dirs = [
    "~/graphics/default/Downloaded-Mods-1.15.x/"
]
patches_dir = "~/graphics/default/Modded-1.15.x/"
pack_dir = "~/graphics_merged/default/Modded-1.15.x/"
pack_format = 5



# FANVER RESOURCES
["fanver-vanilla-1.5.x"]
download_url = "http://dl.soartex.net/xv78o"
download_dir = "~/graphics/fanver/Vanilla-1.5.x/Vanilla/"
patches_dir = "~/graphics/fanver/Vanilla-1.5.x/"
pack_dir = "~/graphics/fanver/Vanilla-1.5.x/Vanilla/"
link_dirs = [
    "/Applications/MultiMC.app/Contents/MacOS/instances/FTB Infinity Evolved 1.7/.minecraft/resourcepacks/Fanver_Vanilla",
    "/Applications/MultiMC.app/Contents/MacOS/instances/1.7.10/.minecraft/resourcepacks/Fanver_Vanilla"
]

["fanver-vanilla-1.7.x"]
download_project_id = 42794
download_file_id = 2208964
download_dir = "~/graphics/fanver/Vanilla-1.7.x/Vanilla/"
patches_dir = "~/graphics/fanver/Vanilla-1.7.x/"
pack_dir = "~/graphics/fanver/Vanilla-1.7.x/Vanilla/"
link_dirs = [
    "/Applications/MultiMC.app/Contents/MacOS/instances/FTB Infinity Evolved 1.7/.minecraft/resourcepacks/Fanver_Vanilla",
    "/Applications/MultiMC.app/Contents/MacOS/instances/1.7.10/.minecraft/resourcepacks/Fanver_Vanilla"
]

["fanver-vanilla-1.10.x"]
download_project_id = 42794
download_file_id = 2315779
download_dir = "~/graphics/fanver/Vanilla-1.10.x/Vanilla/"
patches_dir = "~/graphics/fanver/Vanilla-1.10.x/"
pack_dir = "~/graphics/fanver/Vanilla-1.10.x/Vanilla/"

["fanver-vanilla-1.12.x"]
download_project_id = 42794
download_file_id = 2544544
download_dir = "~/graphics/fanver/Vanilla-1.12.x/Vanilla/"
patches_dir = "~/graphics/fanver/Vanilla-1.12.x/"
pack_dir = "~/graphics/fanver/Vanilla-1.12.x/Vanilla/"
link_dirs = [
    "/Applications/MultiMC.app/Contents/MacOS/instances/FTB Revelation/.minecraft/resourcepacks/Vanilla_Fanver"
]


["fanver-modded-1.5.x"]
download_repo = "git@github.com:Soartex-Modded/Modded-1.5.x.git"
download_dir = "~/graphics/fanver/Modded-1.5.x/"
patches_dir = "~/graphics/fanver/Modded-1.5.x/"
pack_format = 1
pack_dir = "~/graphics_merged/fanver/Modded-1.5.x/"

["fanver-modded-1.7.x"]
download_repo = "git@github.com:Soartex-Modded/Modded-1.7.x.git"
download_dir = "~/graphics/fanver/Modded-1.7.x/"
patches_dir = "~/graphics/fanver/Modded-1.7.x/"
pack_dir = "~/graphics_merged/fanver/Modded-1.7.x/"
pack_format = 1
link_dirs = [
    "/Applications/MultiMC.app/Contents/MacOS/instances/FTB Infinity Evolved 1.7/.minecraft/resourcepacks/Fanver_Modded",
    "/Applications/MultiMC.app/Contents/MacOS/instances/1.7.10/.minecraft/resourcepacks/Fanver_Modded"
]

["fanver-modded-1.10.x"]
download_repo = "git@github.com:Soartex-Modded/Modded-1.10.x.git"
download_dir = "~/graphics/fanver/Modded-1.10.x/"
patches_dir = "~/graphics/fanver/Modded-1.10.x/"
pack_dir = "~/graphics_merged/fanver/Modded-1.10.x/"
pack_format = 2

["fanver-modded-1.12.x"]
download_repo = "git@github.com:Soartex-Modded/Modded-1.12.x.git"
download_dir = "~/graphics/fanver/Modded-1.12.x/"
patches_dir = "~/graphics/fanver/Modded-1.12.x/"
pack_dir = "~/graphics_merged/fanver/Modded-1.12.x/"
pack_format = 3
link_dirs = [
    "/Applications/MultiMC.app/Contents/MacOS/instances/FTB Revelation/.minecraft/resourcepacks/Modded_Fanver"
]

["fanver-modded-1.15.x"]
patches_dir = "~/graphics/fanver/Modded-1.15.x/"
pack_dir = "~/graphics_merged/fanver/Modded-1.15.x/"
pack_format = 5



# INVICTUS RESOURCES
["invictus-vanilla-1.7.x"]
download_project_id = 220720
download_file_id = 2218998
download_dir = "~/graphics/invictus/Vanilla-1.7.x/Vanilla/"
patches_dir = "~/graphics/invictus/Vanilla-1.7.x/"
pack_dir = "~/graphics/invictus/Vanilla-1.7.x/Vanilla/"
link_dirs = [
    "/Applications/MultiMC.app/Contents/MacOS/instances/FTB Infinity Evolved 1.7/.minecraft/resourcepacks/Vanilla_Invictus",
    "/Applications/MultiMC.app/Contents/MacOS/instances/1.7.10/.minecraft/resourcepacks/Vanilla_Invictus"
]

["invictus-vanilla-1.12.x"]
download_project_id = 220720
download_file_id = 2492453
download_dir = "~/graphics/invictus/Vanilla-1.12.x/Vanilla/"
patches_dir = "~/graphics/invictus/Vanilla-1.12.x/"
pack_dir = "~/graphics/invictus/Vanilla-1.12.x/Vanilla/"
link_dirs = [
    "/Applications/MultiMC.app/Contents/MacOS/instances/FTB Revelation/.minecraft/resourcepacks/Vanilla_Invictus"
]

["invictus-modded-1.7.x"]
download_repo = "git@github.com:InvictusGraphics/Modded-1.7.x.git"
download_dir = "~/graphics/invictus/Modded-1.7.x/"
patches_dir = "~/graphics/invictus/Modded-1.7.x/"
pack_format = 1
pack_dir = "~/graphics_merged/invictus/Modded-1.7.x/"
link_dirs = [
    "/Applications/MultiMC.app/Contents/MacOS/instances/FTB Infinity Evolved 1.7/.minecraft/resourcepacks/Modded_Invictus",
    "/Applications/MultiMC.app/Contents/MacOS/instances/1.7.10/.minecraft/resourcepacks/Modded_Invictus"
]



# MISC RESOURCES
["fanver-modded-base"]
download_repo = "git@github.com:Soartex-Modded/Soartex-Modded-Base.git"
download_dir = "~/graphics/fanver/Modded-Base/Soartex-Modded-Base/"
patches_dir = "~/graphics/fanver/Modded-Base/"
pack_dir = "~/graphics_merged/fanver/Modded-Base/"
pack_format = 3
link_dirs = [
    "/Applications/MultiMC.app/Contents/MacOS/instances/FTB Revelation/.minecraft/resourcepacks/Modded_Fanver_Base"
]

["gtnh-1.7.x"]
download_repo = "https://github.com/GTNewHorizons/GTNH-Soartex-Overrides.git"
download_dir = "~/graphics/fanver/GTNH-Soartex-Overrides/"
pack_dir = "~/graphics/fanver/GTNH-Soartex-Overrides/resourcepacks/GTNH-Soartex-Overrides/"
link_dirs = [
    "/Applications/MultiMC.app/Contents/MacOS/instances/1.7.10/.minecraft/resourcepacks/GTNH_Overrides"
]

["modded-server-data"]
download_repo = "git@github.com:Soartex-Modded/Modded-Server-Data.git"
download_dir = "~/graphics/fanver/Modded-Server-Data/"


# JSTR RESOURCES
["jstr-vanilla-1.7.x"]
download_repo = "git@github.com:John-Smith-Modded/JSTR-Vanilla-1.7.x.git"
download_dir = "~/graphics/jstr/Vanilla-1.7.x/Vanilla/"
patches_dir = "~/graphics/jstr/Vanilla-1.7.x/"
pack_dir = "~/graphics/jstr/Vanilla-1.7.x/Vanilla/"

["jstr-vanilla-1.10.x"]
download_repo = "git@github.com:John-Smith-Modded/JSTR-Vanilla-1.10.x.git"
download_dir = "~/graphics/jstr/Vanilla-1.10.x/Vanilla/"
patches_dir = "~/graphics/jstr/Vanilla-1.10.x/"
pack_dir = "~/graphics/jstr/Vanilla-1.10.x/Vanilla/"

["jstr-vanilla-1.12.x"]
download_repo = "git@github.com:John-Smith-Modded/JSTR-Vanilla-1.12.x.git"
download_dir = "~/graphics/jstr/Vanilla-1.12.x/Vanilla/"
patches_dir = "~/graphics/jstr/Vanilla-1.12.x/"
pack_dir = "~/graphics/jstr/Vanilla-1.12.x/Vanilla/"


["jstr-modded-1.5.x"]
download_repo = "git@github.com:John-Smith-Modded/JSTR-Modded-1.5.x.git"
download_dir = "~/graphics/jstr/Modded-1.5.x/"
patches_dir = "~/graphics/jstr/Modded-1.5.x/"
pack_format = 1
pack_dir = "~/graphics_merged/jstr/Modded-1.5.x/"

["jstr-modded-1.7.x"]
download_repo = "git@github.com:John-Smith-Modded/JSTR-Modded-1.7.x.git"
download_dir = "~/graphics/jstr/Modded-1.7.x/"
patches_dir = "~/graphics/jstr/Modded-1.7.x/"
pack_format = 1
pack_dir = "~/graphics_merged/jstr/Modded-1.7.x/"

["jstr-modded-1.10.x"]
download_repo = "git@github.com:John-Smith-Modded/JSTR-Modded-1.10.x.git"
download_dir = "~/graphics/jstr/Modded-1.10.x/"
patches_dir = "~/graphics/jstr/Modded-1.10.x/"
pack_format = 2
pack_dir = "~/graphics_merged/jstr/Modded-1.10.x/"

["jstr-modded-1.12.x"]
download_repo = "git@github.com:John-Smith-Modded/JSTR-Modded-1.12.x.git"
download_dir = "~/graphics/jstr/Modded-1.12.x/"
patches_dir = "~/graphics/jstr/Modded-1.12.x/"
pack_format = 3
pack_dir = "~/graphics_merged/jstr/Modded-1.12.x/"

["jstr-modded-1.15.x"]
patches_dir = "~/graphics/jstr/Modded-1.15.x/"
pack_dir = "~/graphics_merged/jstr/Modded-1.15.x/"
pack_format = 5
